Bandage box mechanic
teambluemods/healthmod-forge pull request #3
Opened 2021-01-25 10:49 UTC by bioastroiner

adding features to bandage box
the box consists of 6 inventory slots for storing various bandages

- [x] ContainerClass
- [x] TileEntityClass
- [ ] OpenGUIlogic
- [ ] InventoryLogic(only allows certain items to be placed in)

2021-01-25 11:19 UTC, bioastroiner commented
should i make this PR a draft? cause i am not done yet.

2021-01-26 06:04 UTC, xf8b commented
uhh your pr is just changing the imports. is this intended or did you mess up while committing?

2021-01-26 14:38 UTC, bioastroiner commented
> uhh your pr is just changing the imports. is this intended or did you mess up while committing?

in the first commit 731c9ac there was still blueminecraftmods instead of teambluemods in the package name in all files, so i changed it and it affected some imports.

2021-01-26 18:16 UTC, bioastroiner commented
> 
> 
> uhh your pr is just changing the imports. is this intended or did you mess up while committing?

ooooooooh holy shit
broh
i have no idea why it just commited just the import

2021-01-26 18:19 UTC, bioastroiner commented
i think i actulley reverted some of my commit
broh some code is gone

2021-01-27 17:55 UTC, zAG6z submitted a review, later dismissed
seems alright to me i think

2021-01-27 17:55 UTC, zAG6z commented
oh shit i pressed somethin

2021-01-27 19:11 UTC, bioastroiner commented
okay checklists tiked
only Binding Screen to Container Bruhcode witch i donno its kotling, maybe few twaeks to screen class

2021-01-27 19:39 UTC, TheOnlyTails requested changes
Some changes are still needed. Also, figure out why the checks are failing.

2021-01-27 19:39 UTC, TheOnlyTails commented on src/main/kotlin/io/github/teambluemods/healthmod/client/HealthModClient.kt
> +        //FIXME i have no idea how to BandageBoxScreen::new in freaking kotling, this lang is not like java
`{ BandageBoxScreen() }`

2021-01-27 19:39 UTC, TheOnlyTails commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +                    tile as BandageBoxTileEntity?,
You don't need to cast here. smart casting is a thing in kotlin.

2021-01-27 19:39 UTC, TheOnlyTails commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +                    (te as BandageBoxTileEntity?)?.items
See previous comment.

2021-01-27 20:01 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/client/HealthModClient.kt
> +        //FIXME i have no idea how to BandageBoxScreen::new in freaking kotling, this lang is not like java
::BandageBoxScreen

2021-01-27 20:02 UTC, xf8b commented
wtf why are you requesting everyone, you only need 2 people to review

2021-01-27 20:10 UTC, xf8b requested changes
multiple code guideline violations. otherwise looks ok

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/client/screen/BandageBoxScreen.kt
> +    ContainerScreen<BandageBoxContainer>(screenContainer, inventory, titleIn) {
this is not how you do constructors

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/client/screen/BandageBoxScreen.kt
> +//    constructor() : this(ContainerTypeRegistries.BANDAGE_BOX.create(10,inventory),inventory = ) {
```kt
constructor(inventory: PlayerInventory, title: ITextComponent) : this(
    ContainerTypeRegistries.BANDAGE_BOX.create(10, inventory), 
    inventory, 
    title
)
```

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/client/screen/BandageBoxScreen.kt
> +        val x: Int = (width - this.xSize) / 2
don't need to specify type. see style guide

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/client/screen/BandageBoxScreen.kt
> +        val y: Int = (height - this.ySize) / 2
*See previous comment.*

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +            if (tile is BandageBoxTileEntity) {
new line before if. see code guidelines

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +                    tile as BandageBoxTileEntity?,
also no need to spread the args over multiple lines

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +            return ActionResultType.SUCCESS
new line before return. see code guidelines.

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +        return ActionResultType.FAIL
*See previous comment.*

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +        if (state.block !== newState.block) {
this is == not .equals

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +            if (te is BandageBoxTileEntity) {
new line before if. see code guidelines.

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +            val te = worldIn.getTileEntity(pos)
descriptive names. see code guidelines

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
> +     * @param dx is gap size
descriptive names. see code guidelines.

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
> +        addSlotBox(playerInventory, 9, leftCol, topRow, 9, 18, 3, 18)
leftColumn. see code guidelines

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
> +     * @param dx x gap
descriptive names. see code guidelines.

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
> +     * @param dy y gap
*See previous comment.*

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
> +            itemstack = itemstack1.copy()
camel case. see code guidelines

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BandageBoxTileEntity.kt
> +    private val handler: ItemStackHandler = createHandler()
no need to specify type. see code guidelines

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BandageBoxTileEntity.kt
> +            override fun isItemValid(slot: Int, @Nonnull stack: ItemStack): Boolean {
no need for nonnull. this is already not null

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BandageBoxTileEntity.kt
> +                return stack.item === ItemRegistries.BANDAGE
use expression. see guide guidelines.

2021-01-27 20:10 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BandageBoxTileEntity.kt
> +                return if (stack.item !== ItemRegistries.BANDAGE) {
use expression, remove {}. see code guidelines.

2021-01-27 20:11 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
> +        if (state.block !== newState.block) {
oh wait nvm

2021-01-27 20:23 UTC, xf8b commented on src/main/kotlin/io/github/teambluemods/healthmod/client/HealthModClient.kt
> +        //ScreenManager.registerFactory(ContainerTypeRegistries.BANDAGE_BOX,BandageBoxScreen)
```suggestion
        ScreenManager.registerFactory(ContainerTypeRegistries.BANDAGE_BOX, ::BandageBoxScreen)
```

2021-01-28 03:12 UTC, xf8b submitted a review, later dismissed
looks good i think

2021-01-28 03:42 UTC, xf8b approved these changes

2021-01-28 04:48 UTC, saksham4106 approved these changes
I feel that it is good

2021-01-28 04:58 UTC, KingRealzYT commented
why did i get a email saying i have to review this? if i do
yea this seems good 
If i dont
Goodbye

2021-01-28 05:28 UTC, xf8b commented
you did before but idk why bioast requested you

2021-01-28 07:26 UTC, TheOnlyTails approved these changes
Lgtm

2021-01-28 14:16 UTC, zAG6z commented
ok

2021-01-28 14:16 UTC, zAG6z approved these changes

2021-01-28 14:43 UTC, KingRealzYT commented
Guess I'm just **built different**

2021-01-28 15:05 UTC, bioastroiner commented
> 
> 
> Guess I'm just **built different**

yea didn't you were play tester ooops

2021-01-28 15:08 UTC, merged